name: Check coding style

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone supercharge docs repository
        uses: actions/checkout@v2
        with:
          repository: ronanboiteau/NormEZ

      - name: NormEZ exec
        run: ./NormEZ/NormEZ.rb
