name: Run tests

on:
  completion:
    success:
    - Check_compilation

jobs:
  build:
    runs-on: ubuntu-20.04

    container: epitechcontent/epitest-docker:devel

    steps:
      - name: unit-tests
        uses: actions/checkout@v2
      - name: make tests command
        run: make tests_run

  build:
    runs-on: ubuntu-20.04

    container: epitechcontent/epitest-docker:devel

    steps:
      - name: functional-tests
        uses: actions/checkout@v2
      - name: make tests command
        run: make tests_run
