name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    container: epitechcontent/epitest-docker:devel

    steps:
      - name: unit-tests
        uses: actions/checkout@v2
      - name: make tests command
        run: make tests_run

jobs:
  build:
    runs-on: ubuntu-20.04

    container: epitechcontent/epitest-docker:devel

    steps:
      - name: functional-tests
        uses: actions/checkout@v2
      - name: make tests command
        run: make tests_run
