name: Build master

on: [push]

strategy:
  matrix:
    compiler: [gcc]

jobs:
  build:
    runs-on: ubuntu-20.04

    container: epitechcontent/epitest-docker:devel

    steps:
      - name: Check compilation
        uses: actions/checkout@v2
      - name: make command
        run: make
